x = int(input("x: "))
y = int(input("y: "))
print(str(x) + " < " + str(y) + " = " + str(x < y))
print(str(x) + " > " + str(y) + " = " + str(x > y))
print(str(x) + " = " + str(y) + " = " + str(x == y))
print(str(x) + " != " + str(y) + " = " + str(x != y))
print(str(x) + " >= " + str(y) + " = " + str(x >= y))
print(str(x) + " <= " + str(y) + " = " + str(x <= y))